name: Build of the project
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Checkout and fetch repo
        uses: actions/checkout@v3
      - name: Get Yarn Cache folder
      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup cache
        uses: actions/cache@v3
      - with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install node packages
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
